disabled_plugins = ["cri"]
root = "/fccd/var/lib/firecracker-containerd/containerd" # Changed!
state = "/run/firecracker-containerd"
[grpc]
  address = "/run/firecracker-containerd/containerd.sock"
[plugins]
  [plugins.devmapper]
    pool_name = "fc-dev-thinpool"
    base_image_size = "10GB"
    root_path = "/fccd/var/lib/firecracker-containerd/snapshotter/devmapper" # Changed!

[debug]
  level = "debug"